const users = require('./users/users.service.js');
const facility = require('./facility/facility.service.js');
const careteam = require('./careteam/careteam.service.js');
const location = require('./location/location.service.js');
const employee = require('./employee/employee.service.js');
const department = require('./department/department.service.js');
const hsModules = require('./hs-modules/hs-modules.service.js');
const workspace = require('./workspace/workspace.service.js');
const roaster = require('./roaster/roaster.service.js');
const deptUnit = require('./dept-unit/dept-unit.service.js');
const billing = require('./billing/billing.service.js');
const mailer = require('./mailer/mailer.service.js');
const authmanagement = require('./authmanagement/authmanagement.service.js');
const products = require('./products/products.service.js');
const inventory = require('./inventory/inventory.service.js');
const productbatch = require('./productbatch/productbatch.service.js');
const productentry = require('./productentry/productentry.service.js');
const inventorytransaction = require('./inventorytransaction/inventorytransaction.service.js');
const client = require('./client/client.service.js');
const documentation = require('./documentation/documentation.service.js');
const episodeOfCare = require('./episode-of-care/episode-of-care.service.js');
const encounter = require('./encounter/encounter.service.js');
const documentclass = require('./documentclass/documentclass.service.js');
const clinicaldocument = require('./clinicaldocument/clinicaldocument.service.js');
const appointments = require('./appointments/appointments.service.js');
const order = require('./order/order.service.js');
const medication = require('./medication/medication.service.js');
const treatmentsheet = require('./treatmentsheet/treatmentsheet.service.js');
const medicationhelper = require('./medicationhelper/medicationhelper.service.js');
const task = require('./task/task.service.js');
const problem = require('./problem/problem.service.js');
const bills = require('./bills/bills.service.js');
const orderbillhelper = require('./orderbillhelper/orderbillhelper.service.js');
const wallet = require('./wallet/wallet.service.js');
const wallettransaction = require('./wallettransaction/wallettransaction.service.js');
const subwallet = require('./subwallet/subwallet.service.js');
//const subwallettranasactions = require('./subwallettranasactions/subwallettranasactions.service.js');
const subwallettransactions = require('./subwallettransactions/subwallettransactions.service.js');
const invoice = require('./invoice/invoice.service.js');
const billcreation = require('./billcreation/billcreation.service.js');
const createbilldirect = require('./createbilldirect/createbilldirect.service.js');
const labhelper = require('./labhelper/labhelper.service.js');
const labresults = require('./labresults/labresults.service.js');
const oldapmispatient = require('./oldapmispatient/oldapmispatient.service.js');
const oldapmispeople = require('./oldapmispeople/oldapmispeople.service.js');
const foremost = require('./foremost/foremost.service.js');
const mpi = require('./mpi/mpi.service.js');
// const upload = require('./upload/upload.service.js');
const organizationclient = require('./organizationclient/organizationclient.service.js');
const bands = require('./bands/bands.service.js');
const casedefinition = require('./casedefinition/casedefinition.service.js');
const epidmatch = require('./epidmatch/epidmatch.service.js');
const whatsappapi = require('./whatsappapi/whatsappapi.service.js');
const epidalerts = require('./epidalerts/epidalerts.service.js');
const admission = require('./admission/admission.service.js');
const chartsofaccount = require('./chartsofaccount/chartsofaccount.service.js');
const expense = require('./expense/expense.service.js');
const bank = require('./bank/bank.service.js');
const referral = require('./referral/referral.service.js');
const notification = require('./notification/notification.service.js');
const policy = require('./policy/policy.service.js');
const chartaccounts = require('./chartaccounts/chartaccounts.service.js');
const acctblledger = require('./acctblledger/acctblledger.service.js');
const acctransactions = require('./acctransactions/acctransactions.service.js');
const accorderDetails = require('./accorder_details/accorder_details.service.js');
const accpersons = require('./accpersons/accpersons.service.js');
const deal = require('./deal/deal.service.js');
const claims = require('./claims/claims.service.js');
const preauth = require('./preauth/preauth.service.js');
const providerpayment = require('./providerpayment/providerpayment.service.js');
const healthplan = require('./healthplan/healthplan.service.js');
const complaints = require('./complaints/complaints.service.js');
const vaccine = require('./vaccine/vaccine.service.js');
const vaccineprofile = require('./vaccineprofile/vaccineprofile.service.js');
const immunizationschedule = require('./immunizationschedule/immunizationschedule.service.js');
const utilization = require('./utilization/utilization.service.js');
const mei = require('./mei/mei.service.js');
const otp = require('./otp/otp.service.js');
const accreditation = require('./accreditation/accreditation.service.js');
const templatedoc = require('./templatedoc/templatedoc.service.js');
const email = require('./email/email.service.js');
const facilityConfig = require('./facility-config/facility-config.service.js');
const tariff = require('./tariff/tariff.service.js');
const fundmgt = require('./fundmgt/fundmgt.service.js');
const extpolicy = require('./extpolicy/extpolicy.service.js');
const icd11 = require('./icd11/icd11.service.js');
const chat = require('./chat/chat.service.js');
const chatroom = require('./chatroom/chatroom.service.js');
const members = require('./members/members.service.js');
const transfer = require('./transfer/transfer.service.js');
const hstranstactions = require('./hstranstactions/hstranstactions.service.js');
const sendsms = require('./sendsms/sendsms.service.js');
const extsubwallet = require('./extsubwallet/extsubwallet.service.js');
const extbills = require('./extbills/extbills.service.js');
const extsubtx = require('./extsubtx/extsubtx.service.js');
const fintrx = require('./fintrx/fintrx.service.js');
const premiums = require('./premiums/premiums.service.js');
const corpinvoices = require('./corpinvoices/corpinvoices.service.js');
const logins = require('./logins/logins.service.js');
const loginanlytics = require('./loginanlytics/loginanlytics.service.js');
const hmoanalytics = require('./hmoanalytics/hmoanalytics.service.js');
const payanalytics = require('./payanalytics/payanalytics.service.js');
const paygtransc = require('./paygtransc/paygtransc.service.js');
const labrefvalue = require('./labrefvalue/labrefvalue.service.js');
const familyprofile = require('./familyprofile/familyprofile.service.js');
const malehx = require('./malehx/malehx.service.js');
const femalehx = require('./femalehx/femalehx.service.js');
const uploadlocal = require('./uploadlocal/uploadlocal.service.js');
//const authMgt = require('./auth-mgt/auth-mgt.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
 app.configure(users);
 app.configure(facility);
 app.configure(careteam);
 app.configure(location);
 app.configure(employee);
 app.configure(department);
 app.configure(hsModules);
 app.configure(workspace);
 app.configure(roaster);
 app.configure(deptUnit);
 app.configure(billing);
 app.configure(mailer);
 //app.configure(authMgt);
 app.configure(authmanagement);
 app.configure(products);
 app.configure(inventory);
 app.configure(productbatch);
 app.configure(productentry);
 app.configure(inventorytransaction);
 app.configure(client);
 app.configure(documentation);
 app.configure(episodeOfCare);
 app.configure(encounter);
 app.configure(documentclass);
 app.configure(clinicaldocument);
 app.configure(appointments);
 app.configure(order);
 app.configure(medication);
 app.configure(treatmentsheet);
 app.configure(medicationhelper);
 app.configure(task);
 app.configure(problem);
 app.configure(bills);
 app.configure(orderbillhelper);
 app.configure(wallet);
 app.configure(wallettransaction);
 app.configure(subwallet);
 // app.configure(subwallettranasactions);
 app.configure(subwallettransactions);
 app.configure(invoice);
 app.configure(billcreation);
 app.configure(createbilldirect);
 app.configure(labhelper);
 app.configure(labresults);
 app.configure(oldapmispatient);
 app.configure(oldapmispeople);
 app.configure(foremost);
 app.configure(mpi);
//  app.configure(upload);
 app.configure(organizationclient);
 app.configure(bands);
 app.configure(casedefinition);
 app.configure(epidmatch);
 app.configure(whatsappapi);
 app.configure(epidalerts);
 app.configure(admission);
 app.configure(chartsofaccount);
 app.configure(expense);
 app.configure(bank);
 app.configure(referral);
 app.configure(notification);
 app.configure(policy);
 app.configure(chartaccounts);
 app.configure(acctblledger);
 app.configure(acctransactions);
 app.configure(accorderDetails);
 app.configure(accpersons);
 app.configure(deal);
 app.configure(claims);
 app.configure(preauth);
 app.configure(providerpayment);
 app.configure(healthplan);
 app.configure(complaints);
 app.configure(vaccine);
 app.configure(vaccineprofile);
 app.configure(immunizationschedule);
 app.configure(utilization);
 app.configure(mei);
 app.configure(otp);
 app.configure(accreditation);
 app.configure(templatedoc);
 app.configure(email);
 app.configure(facilityConfig);
 app.configure(tariff);
 app.configure(fundmgt);
 app.configure(extpolicy);
 app.configure(icd11);
 app.configure(chat);
 app.configure(chatroom);
 app.configure(members);
 app.configure(transfer);
 app.configure(hstranstactions);
 app.configure(sendsms);
 app.configure(extsubwallet);
 app.configure(extbills);
 app.configure(extsubtx);
 app.configure(fintrx);
 app.configure(premiums);
 app.configure(corpinvoices);
 app.configure(logins);
 app.configure(loginanlytics);
 app.configure(hmoanalytics);
 app.configure(payanalytics);
 app.configure(paygtransc);
 app.configure(labrefvalue);
 app.configure(familyprofile);
 app.configure(malehx);
 app.configure(femalehx);
 app.configure(uploadlocal);
};
